// ─── FitBuddy 2.0 Exercise Database (60+ exercises) ────────────────────────

export const CATEGORIES = {
  CHEST:      'Chest',
  BACK:       'Back',
  LEGS:       'Legs',
  SHOULDERS:  'Shoulders',
  ARMS:       'Arms',
  CORE:       'Core',
  GLUTES:     'Glutes',
  CARDIO:     'Cardio',
  FULL_BODY:  'Full Body',
  MOBILITY:   'Mobility',
};

export const EQUIPMENT = {
  BODYWEIGHT: 'bodyweight',
  DUMBBELLS:  'dumbbells',
  BANDS:      'bands',
  GYM:        'gym',
};

export const EXERCISES = [
  // ── CHEST ──────────────────────────────────────────────────────────────
  {
    id: 'push_up', name: 'Push-ups', category: CATEGORIES.CHEST,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Chest', 'Triceps', 'Front Delt', 'Core'],
    calsPerMin: 7, sets: 3, reps: '12–15', rest: 60,
    instructions: 'Start in a high plank with hands shoulder-width apart. Lower your chest to just above the floor, keeping your body in a straight line. Push back up explosively.',
    tip: 'Keep your elbows at 45° to your torso — never flare out. Exhale at the top.',
    benefits: ['Builds upper-body pushing strength', 'Engages core stabilisers', 'No equipment needed'],
  },
  {
    id: 'incline_push_up', name: 'Incline Push-ups', category: CATEGORIES.CHEST,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Lower Chest', 'Triceps', 'Core'],
    calsPerMin: 6, sets: 3, reps: '12–15', rest: 60,
    instructions: 'Place hands on an elevated surface (chair/bed). Perform a push-up while keeping your body rigid. Easier than standard push-ups.',
    tip: 'Great for beginners. Progress by lowering the surface height over time.',
    benefits: ['Easier entry to push-ups', 'Targets lower chest', 'Adjustable difficulty'],
  },
  {
    id: 'db_chest_press', name: 'Dumbbell Chest Press', category: CATEGORIES.CHEST,
    equipment: EQUIPMENT.DUMBBELLS, difficulty: 'intermediate',
    muscles: ['Chest', 'Triceps', 'Front Delt'],
    calsPerMin: 6, sets: 3, reps: '10–12', rest: 75,
    instructions: 'Lie on a flat surface. Hold dumbbells at chest level with elbows at 45°. Press up until arms are fully extended, then lower slowly over 2 seconds.',
    tip: 'Control the descent — 2 seconds down, 1 second pause, push up powerfully.',
    benefits: ['Greater range of motion than barbell', 'Corrects muscle imbalances', 'Deep chest stretch'],
  },
  {
    id: 'db_flyes', name: 'Dumbbell Flyes', category: CATEGORIES.CHEST,
    equipment: EQUIPMENT.DUMBBELLS, difficulty: 'intermediate',
    muscles: ['Chest', 'Front Delt'],
    calsPerMin: 5, sets: 3, reps: '10–12', rest: 75,
    instructions: 'Lie flat. Arms extended above chest with slight elbow bend. Lower dumbbells in a wide arc until you feel a deep chest stretch. Squeeze them back up.',
    tip: 'Think of hugging a giant tree. Never lock your elbows fully.',
    benefits: ['Deep pectoral stretch', 'Great for chest definition', 'Isolation movement'],
  },
  {
    id: 'diamond_push_up', name: 'Diamond Push-ups', category: CATEGORIES.CHEST,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'intermediate',
    muscles: ['Inner Chest', 'Triceps'],
    calsPerMin: 8, sets: 3, reps: '8–12', rest: 75,
    instructions: 'Form a diamond with your thumbs and index fingers beneath your chest. Lower chest to hands, keeping elbows close to body. Push back up.',
    tip: 'If wrists hurt, use push-up handles or make fists. Go slow.',
    benefits: ['Targets inner chest and triceps', 'No equipment', 'Brutal tricep builder'],
  },

  // ── BACK ───────────────────────────────────────────────────────────────
  {
    id: 'pull_up', name: 'Pull-ups', category: CATEGORIES.BACK,
    equipment: EQUIPMENT.GYM, difficulty: 'advanced',
    muscles: ['Lats', 'Biceps', 'Rear Delt', 'Core'],
    calsPerMin: 9, sets: 3, reps: '6–10', rest: 90,
    instructions: 'Hang from bar, overhand grip slightly wider than shoulders. Retract shoulder blades. Pull chin over bar. Lower under control.',
    tip: 'Initiate with your back, not your arms. Imagine bending the bar towards you.',
    benefits: ['Ultimate back builder', 'Improves grip strength', 'Decompresses spine'],
  },
  {
    id: 'db_row', name: 'Single-Arm Dumbbell Row', category: CATEGORIES.BACK,
    equipment: EQUIPMENT.DUMBBELLS, difficulty: 'intermediate',
    muscles: ['Lats', 'Rhomboids', 'Rear Delt', 'Biceps'],
    calsPerMin: 6, sets: 3, reps: '10–12 each', rest: 75,
    instructions: 'One knee on a bench, supporting hand on bench. Pull dumbbell from hanging position to your hip. Keep back flat.',
    tip: 'Squeeze your shoulder blade at the top — pause for 1 second there.',
    benefits: ['Builds thick back', 'Corrects imbalances', 'Supports lower back'],
  },
  {
    id: 'superman', name: 'Superman Hold', category: CATEGORIES.BACK,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Lower Back', 'Glutes', 'Hamstrings'],
    calsPerMin: 4, sets: 3, reps: '12 (2s hold)', rest: 60,
    instructions: 'Lie face down. Extend arms forward. Simultaneously lift arms, chest, and legs off the floor. Hold 2 seconds. Lower.',
    tip: 'Squeeze your glutes and think about making yourself as long as possible.',
    benefits: ['Strengthens lower back', 'Counters desk posture', 'Improves posture'],
  },
  {
    id: 'band_row', name: 'Resistance Band Row', category: CATEGORIES.BACK,
    equipment: EQUIPMENT.BANDS, difficulty: 'beginner',
    muscles: ['Lats', 'Rhomboids', 'Rear Delt'],
    calsPerMin: 5, sets: 3, reps: '12–15', rest: 60,
    instructions: 'Anchor band at waist height. Step back, pull handles towards your torso with elbows at 45°. Squeeze shoulder blades together.',
    tip: 'Focus on pulling with your back, not your arms. Slow and controlled.',
    benefits: ['Joint-friendly', 'Constant tension', 'Portable'],
  },
  {
    id: 'face_pull', name: 'Band Face Pulls', category: CATEGORIES.BACK,
    equipment: EQUIPMENT.BANDS, difficulty: 'beginner',
    muscles: ['Rear Delt', 'Rotator Cuff', 'Rhomboids'],
    calsPerMin: 4, sets: 3, reps: '15–20', rest: 60,
    instructions: 'Anchor band at head height. Pull handles to ears with elbows high and flared out. Pause at the end.',
    tip: 'Do these every session — most people have chronically weak rear delts.',
    benefits: ['Fixes rounded shoulders', 'Protects rotator cuff', 'Improves posture'],
  },
  {
    id: 'dead_hang', name: 'Dead Hang', category: CATEGORIES.BACK,
    equipment: EQUIPMENT.GYM, difficulty: 'beginner',
    muscles: ['Lats', 'Grip', 'Core'],
    calsPerMin: 3, sets: 3, reps: '30–60s', rest: 60,
    instructions: 'Simply hang from a pull-up bar with both hands. Keep shoulders engaged (not shrugged). Breathe deeply.',
    tip: 'Best way to decompress the spine and build grip strength. Work up to 60 seconds.',
    benefits: ['Decompresses spine', 'Builds grip', 'Pre-rehab for shoulder'],
  },

  // ── LEGS ───────────────────────────────────────────────────────────────
  {
    id: 'squat', name: 'Air Squats', category: CATEGORIES.LEGS,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Core'],
    calsPerMin: 8, sets: 3, reps: '15–20', rest: 60,
    instructions: 'Feet shoulder-width, toes slightly out. Push hips back and sit down until thighs are parallel to the floor. Drive through heels to stand.',
    tip: 'Keep chest up and knees tracking over toes throughout the movement.',
    benefits: ['Builds leg strength', 'Burns high calories', 'Functional movement'],
  },
  {
    id: 'db_squat', name: 'Dumbbell Squat', category: CATEGORIES.LEGS,
    equipment: EQUIPMENT.DUMBBELLS, difficulty: 'intermediate',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Core'],
    calsPerMin: 9, sets: 3, reps: '12–15', rest: 75,
    instructions: 'Hold dumbbells at shoulders (goblet style or at sides). Perform a squat keeping chest tall and knees out.',
    tip: 'Drive the knees out over your pinky toe. Don\'t let them cave inward.',
    benefits: ['Adds resistance to squats', 'Scalable weight', 'Better quad activation'],
  },
  {
    id: 'lunge', name: 'Walking Lunges', category: CATEGORIES.LEGS,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Balance'],
    calsPerMin: 7, sets: 3, reps: '12 each leg', rest: 60,
    instructions: 'Step forward with one leg and lower your back knee towards the floor. Keep front shin vertical. Push off and bring back leg forward to lunge again.',
    tip: 'Keep your torso upright. Don\'t let front knee pass over toes.',
    benefits: ['Unilateral strength', 'Balance training', 'Functional movement'],
  },
  {
    id: 'romanian_dl', name: 'Romanian Deadlift (DB)', category: CATEGORIES.LEGS,
    equipment: EQUIPMENT.DUMBBELLS, difficulty: 'intermediate',
    muscles: ['Hamstrings', 'Glutes', 'Lower Back'],
    calsPerMin: 7, sets: 3, reps: '10–12', rest: 75,
    instructions: 'Hold dumbbells in front of thighs. Hinge at hips, pushing them back as you lower the weights along your legs. Feel the hamstring stretch. Drive hips forward to stand.',
    tip: 'Maintain a neutral spine — never round your lower back. Soft knees throughout.',
    benefits: ['Hamstring hypertrophy', 'Glute development', 'Injury prevention'],
  },
  {
    id: 'glute_bridge', name: 'Glute Bridge', category: CATEGORIES.GLUTES,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Glutes', 'Hamstrings', 'Lower Back'],
    calsPerMin: 5, sets: 3, reps: '15–20', rest: 60,
    instructions: 'Lie on back, knees bent, feet flat. Drive hips up by squeezing glutes until body forms a straight line from knees to shoulders. Hold 1s at the top.',
    tip: 'Press through your heels, not your toes. Squeeze hard at the top.',
    benefits: ['Activates glutes', 'Reduces back pain', 'Great for beginners'],
  },
  {
    id: 'jump_squat', name: 'Jump Squats', category: CATEGORIES.LEGS,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'intermediate',
    muscles: ['Quads', 'Glutes', 'Calves', 'Cardio'],
    calsPerMin: 12, sets: 3, reps: '10–15', rest: 90,
    instructions: 'Perform a squat then explode upward, leaving the floor. Land softly with bent knees. Immediately go into next rep.',
    tip: 'Land heel-to-toe. Never lock knees on landing. Great for power and fat burning.',
    benefits: ['Power development', 'High calorie burn', 'Athletic performance'],
  },
  {
    id: 'wall_sit', name: 'Wall Sit', category: CATEGORIES.LEGS,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Quads', 'Glutes', 'Core'],
    calsPerMin: 5, sets: 3, reps: '30–60s hold', rest: 60,
    instructions: 'Back flat against wall, slide down until thighs are parallel to the floor. Hold. Feet flat, knees at 90°.',
    tip: 'Don\'t rest hands on thighs. Hold your arms out in front to increase difficulty.',
    benefits: ['Isometric quad strength', 'No equipment', 'Mental toughness'],
  },
  {
    id: 'calf_raise', name: 'Calf Raises', category: CATEGORIES.LEGS,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Calves', 'Tibialis'],
    calsPerMin: 4, sets: 3, reps: '20–25', rest: 45,
    instructions: 'Stand tall, feet hip-width. Rise up onto the balls of your feet as high as possible. Hold briefly, then lower slowly.',
    tip: 'Go through full range of motion — squeeze hard at the top, stretch at the bottom.',
    benefits: ['Builds calves', 'Improves ankle stability', 'Good for runners'],
  },

  // ── SHOULDERS ──────────────────────────────────────────────────────────
  {
    id: 'overhead_press', name: 'Dumbbell Overhead Press', category: CATEGORIES.SHOULDERS,
    equipment: EQUIPMENT.DUMBBELLS, difficulty: 'intermediate',
    muscles: ['Front Delt', 'Side Delt', 'Triceps', 'Upper Traps'],
    calsPerMin: 7, sets: 3, reps: '10–12', rest: 75,
    instructions: 'Sit or stand. Hold dumbbells at shoulder height with elbows at 90°. Press straight overhead until arms are fully extended. Lower under control.',
    tip: 'Don\'t arch your lower back. Brace your core throughout the movement.',
    benefits: ['Builds shoulder mass', 'Overhead strength', 'Core engagement'],
  },
  {
    id: 'lateral_raise', name: 'Lateral Raises', category: CATEGORIES.SHOULDERS,
    equipment: EQUIPMENT.DUMBBELLS, difficulty: 'beginner',
    muscles: ['Side Delt'],
    calsPerMin: 5, sets: 3, reps: '12–15', rest: 60,
    instructions: 'Arms at sides, palms facing in. Raise arms out to the side until parallel with the floor. Lead with elbows slightly higher than wrists. Lower slowly.',
    tip: 'Use lighter weight than you think you need. 3-second lowering phase is key.',
    benefits: ['Shoulder width', 'Side delt isolation', 'Creates the "3D shoulder" look'],
  },
  {
    id: 'front_raise', name: 'Front Raises', category: CATEGORIES.SHOULDERS,
    equipment: EQUIPMENT.DUMBBELLS, difficulty: 'beginner',
    muscles: ['Front Delt'],
    calsPerMin: 5, sets: 3, reps: '12–15', rest: 60,
    instructions: 'Arms at sides. Raise one or both dumbbells to shoulder height in front. Keep slight elbow bend. Lower slowly.',
    tip: 'Keep control — avoid swinging. Thumbs slightly up reduces shoulder impingement.',
    benefits: ['Front delt strength', 'Pressing strength carryover'],
  },
  {
    id: 'band_shoulder_press', name: 'Band Shoulder Press', category: CATEGORIES.SHOULDERS,
    equipment: EQUIPMENT.BANDS, difficulty: 'beginner',
    muscles: ['Front Delt', 'Side Delt', 'Triceps'],
    calsPerMin: 6, sets: 3, reps: '12–15', rest: 60,
    instructions: 'Stand on band, hold handles at shoulder height. Press overhead until arms extended. Lower to start.',
    tip: 'Constant tension from bands challenges stabiliser muscles more than dumbbells.',
    benefits: ['Joint-friendly pressing', 'Portable', 'Unilateral option'],
  },
  {
    id: 'pike_push_up', name: 'Pike Push-ups', category: CATEGORIES.SHOULDERS,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'intermediate',
    muscles: ['Front Delt', 'Triceps', 'Upper Chest'],
    calsPerMin: 7, sets: 3, reps: '8–12', rest: 75,
    instructions: 'Start in a downward dog position (inverted V). Bend elbows to lower head toward floor between your hands. Push back up.',
    tip: 'The more vertical your torso, the more it targets shoulders vs chest.',
    benefits: ['Overhead strength without weights', 'Shoulder stability', 'Bodyweight pressing'],
  },

  // ── ARMS ───────────────────────────────────────────────────────────────
  {
    id: 'db_curl', name: 'Dumbbell Bicep Curl', category: CATEGORIES.ARMS,
    equipment: EQUIPMENT.DUMBBELLS, difficulty: 'beginner',
    muscles: ['Biceps', 'Brachialis'],
    calsPerMin: 5, sets: 3, reps: '10–12 each', rest: 60,
    instructions: 'Stand tall, arms at sides with dumbbells. Curl one arm up while keeping elbow pinned to your side. Squeeze at the top. Lower under control.',
    tip: 'Don\'t swing your body. Slow 3-second lowering doubles the results.',
    benefits: ['Bicep mass', 'Arm definition', 'Grip strength'],
  },
  {
    id: 'hammer_curl', name: 'Hammer Curl', category: CATEGORIES.ARMS,
    equipment: EQUIPMENT.DUMBBELLS, difficulty: 'beginner',
    muscles: ['Biceps', 'Brachialis', 'Brachioradialis'],
    calsPerMin: 5, sets: 3, reps: '10–12', rest: 60,
    instructions: 'Palms facing each other (neutral grip). Curl dumbbells up while keeping this neutral position. Lower slowly.',
    tip: 'This builds the brachialis — the muscle under your bicep that makes arms look bigger.',
    benefits: ['Arm thickness', 'Forearm development', 'Grip strength'],
  },
  {
    id: 'tricep_dip', name: 'Tricep Dips (Chair)', category: CATEGORIES.ARMS,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Triceps', 'Front Delt', 'Chest'],
    calsPerMin: 6, sets: 3, reps: '10–15', rest: 60,
    instructions: 'Sit on edge of chair, hands gripping seat. Slide off, lower body by bending elbows to 90°. Push back up. Keep back close to chair.',
    tip: 'Elbows pointing back, not flared. The more you extend legs, the harder it gets.',
    benefits: ['Tricep mass', 'Elbow strength', 'No special equipment'],
  },
  {
    id: 'overhead_tricep', name: 'Overhead Tricep Extension', category: CATEGORIES.ARMS,
    equipment: EQUIPMENT.DUMBBELLS, difficulty: 'intermediate',
    muscles: ['Long Head Tricep'],
    calsPerMin: 5, sets: 3, reps: '10–12', rest: 75,
    instructions: 'Hold one dumbbell with both hands overhead. Lower behind your head by bending elbows. Extend back up.',
    tip: 'Best exercise for the long head of the tricep. Keep upper arms still.',
    benefits: ['Full tricep development', 'Overhead mobility', 'Arm size'],
  },
  {
    id: 'band_curl', name: 'Resistance Band Curl', category: CATEGORIES.ARMS,
    equipment: EQUIPMENT.BANDS, difficulty: 'beginner',
    muscles: ['Biceps'],
    calsPerMin: 4, sets: 3, reps: '12–15', rest: 60,
    instructions: 'Stand on band, hold handles with underhand grip. Curl up squeezing biceps. Constant tension from band.',
    tip: 'The peak tension is at the top of the movement with bands — hold for 2 seconds there.',
    benefits: ['Joint-friendly curls', 'Constant tension', 'Portable'],
  },

  // ── CORE ───────────────────────────────────────────────────────────────
  {
    id: 'plank', name: 'Plank', category: CATEGORIES.CORE,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Core', 'Transverse Abdominis', 'Shoulders'],
    calsPerMin: 4, sets: 3, reps: '30–60s', rest: 45,
    instructions: 'Forearms on floor, elbows under shoulders. Keep body rigid — straight line from head to heels. Don\'t let hips sag or rise.',
    tip: 'Squeeze glutes and try to "pull" elbows towards your feet. Quality over duration.',
    benefits: ['Core stability', 'Posture improvement', 'Foundation movement'],
  },
  {
    id: 'dead_bug', name: 'Dead Bug', category: CATEGORIES.CORE,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Core', 'Transverse Abdominis', 'Hip Flexors'],
    calsPerMin: 4, sets: 3, reps: '10 each side', rest: 45,
    instructions: 'Lie on back, arms pointing at ceiling, knees at 90°. Lower opposite arm and leg simultaneously while pressing lower back into floor. Return. Alternate.',
    tip: 'Go slow. The key is keeping your lower back FLAT on the floor throughout.',
    benefits: ['Deep core activation', 'Back-safe', 'Shoulder coordination'],
  },
  {
    id: 'bicycle_crunch', name: 'Bicycle Crunches', category: CATEGORIES.CORE,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'intermediate',
    muscles: ['Obliques', 'Rectus Abdominis', 'Hip Flexors'],
    calsPerMin: 7, sets: 3, reps: '15–20 each side', rest: 60,
    instructions: 'Hands behind head, legs off floor at 45°. Bring one knee to chest while rotating opposite elbow toward it. Alternate in a cycling motion.',
    tip: 'Slow and controlled — don\'t rush. Focus on the rotation, not crunching.',
    benefits: ['Oblique definition', 'Total ab workout', 'Burns calories'],
  },
  {
    id: 'leg_raise', name: 'Hanging Leg Raises', category: CATEGORIES.CORE,
    equipment: EQUIPMENT.GYM, difficulty: 'advanced',
    muscles: ['Lower Abs', 'Hip Flexors', 'Core'],
    calsPerMin: 6, sets: 3, reps: '10–15', rest: 75,
    instructions: 'Hang from bar. Keep legs straight (or knees bent for easier version). Raise legs to 90° or higher. Lower under control — don\'t swing.',
    tip: 'Posterior tilt your pelvis at the top to fully contract lower abs.',
    benefits: ['Lower ab strength', 'Hip flexor strength', 'Grip training bonus'],
  },
  {
    id: 'russian_twist', name: 'Russian Twist', category: CATEGORIES.CORE,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'intermediate',
    muscles: ['Obliques', 'Core'],
    calsPerMin: 6, sets: 3, reps: '15–20 each side', rest: 60,
    instructions: 'Sit at 45° angle, knees bent, feet off floor. Clasp hands together. Rotate torso side to side, touching the floor each time.',
    tip: 'Keep chest tall and rotate from your torso, not just your arms.',
    benefits: ['Oblique definition', 'Rotational strength', 'Sports performance'],
  },
  {
    id: 'mountain_climber', name: 'Mountain Climbers', category: CATEGORIES.CORE,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'intermediate',
    muscles: ['Core', 'Hip Flexors', 'Cardio', 'Shoulders'],
    calsPerMin: 10, sets: 3, reps: '30–40 reps', rest: 60,
    instructions: 'High plank position. Drive one knee toward your chest, then switch legs rapidly in a running motion while keeping hips level.',
    tip: 'Keep hips from bouncing. Slow it down if your form breaks.',
    benefits: ['Core + cardio combo', 'High calorie burn', 'No equipment'],
  },

  // ── FULL BODY / CARDIO ─────────────────────────────────────────────────
  {
    id: 'burpee', name: 'Burpees', category: CATEGORIES.FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'advanced',
    muscles: ['Full Body', 'Cardio'],
    calsPerMin: 12, sets: 3, reps: '8–12', rest: 90,
    instructions: 'Stand → squat → place hands → jump feet back to plank → push-up → jump feet forward → jump with arms overhead. That\'s one rep.',
    tip: 'Scale it: remove the push-up or the jump at the top. Pace yourself.',
    benefits: ['Maximum calorie burn', 'Full body conditioning', 'No equipment'],
  },
  {
    id: 'jumping_jack', name: 'Jumping Jacks', category: CATEGORIES.CARDIO,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Cardio', 'Full Body'],
    calsPerMin: 9, sets: 3, reps: '30–40', rest: 45,
    instructions: 'Jump feet out while raising arms overhead simultaneously. Jump feet back together while lowering arms. Continuous rhythm.',
    tip: 'Great warm-up or active rest. Keep a soft landing by bending knees slightly.',
    benefits: ['Cardio warm-up', 'Low impact option', 'Full body warm-up'],
  },
  {
    id: 'high_knees', name: 'High Knees', category: CATEGORIES.CARDIO,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Hip Flexors', 'Quads', 'Core', 'Cardio'],
    calsPerMin: 10, sets: 3, reps: '30–40 (or 30s)', rest: 60,
    instructions: 'Run in place, driving knees up to hip height with each step. Pump your arms. Stay on the balls of your feet.',
    tip: 'Hold hands out at hip height as targets for your knees. Land softly.',
    benefits: ['Cardio burst', 'Hip flexor activation', 'Coordination'],
  },
  {
    id: 'bear_crawl', name: 'Bear Crawl', category: CATEGORIES.FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'intermediate',
    muscles: ['Shoulders', 'Core', 'Quads', 'Full Body'],
    calsPerMin: 9, sets: 3, reps: '20m forward + 20m back', rest: 75,
    instructions: 'On all fours with knees hovering 2 inches off the floor. Move opposite hand and foot simultaneously — right hand + left foot, then switch. Keep back flat.',
    tip: 'Move slowly. The goal is stability, not speed. Knees should barely hover.',
    benefits: ['Total body conditioning', 'Core stability', 'Shoulder strength'],
  },
  {
    id: 'step_up', name: 'Step-ups', category: CATEGORIES.LEGS,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Balance'],
    calsPerMin: 6, sets: 3, reps: '12 each leg', rest: 60,
    instructions: 'Step onto a sturdy chair or step with one foot. Drive through that heel to lift your body. Step down with the same foot. Alternate.',
    tip: 'Keep the working leg doing all the work — don\'t push off the trailing foot.',
    benefits: ['Functional strength', 'Glute activation', 'No special equipment'],
  },

  // ── MOBILITY ──────────────────────────────────────────────────────────
  {
    id: 'hip_flexor_stretch', name: 'Hip Flexor Stretch (Kneeling)', category: CATEGORIES.MOBILITY,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Hip Flexors', 'Quads'],
    calsPerMin: 2, sets: 2, reps: '30–45s each side', rest: 30,
    instructions: 'Kneel on one knee, front foot forward at 90°. Gently push hips forward until you feel a stretch in the front of the rear hip.',
    tip: 'Tuck your pelvis slightly to deepen the stretch. Avoid arching lower back.',
    benefits: ['Counters sitting', 'Improves squat depth', 'Reduces back pain'],
  },
  {
    id: 'cat_cow', name: 'Cat-Cow Stretch', category: CATEGORIES.MOBILITY,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Spine', 'Core', 'Hips'],
    calsPerMin: 2, sets: 2, reps: '10 slow cycles', rest: 30,
    instructions: 'On all fours. Inhale: arch your back (cow — belly drops, head up). Exhale: round your back (cat — head down, spine rounds). Flow rhythmically.',
    tip: 'Move with your breath. This is about mobility, not strength.',
    benefits: ['Spinal mobility', 'Back pain relief', 'Morning activation'],
  },
  {
    id: 'world_greatest_stretch', name: 'World\'s Greatest Stretch', category: CATEGORIES.MOBILITY,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Hip Flexors', 'Thoracic Spine', 'Hamstrings', 'Glutes'],
    calsPerMin: 3, sets: 2, reps: '5 each side', rest: 30,
    instructions: 'From a lunge position (right foot forward), place right hand on the floor. Rotate left arm up towards ceiling. Then reach right arm under. Hold each position 2s.',
    tip: 'Perfect pre-workout warmup. Go through it slowly and breathe into each position.',
    benefits: ['Full body mobility', 'Warm-up', 'Injury prevention'],
  },
  {
    id: 'pigeon_pose', name: 'Pigeon Pose', category: CATEGORIES.MOBILITY,
    equipment: EQUIPMENT.BODYWEIGHT, difficulty: 'beginner',
    muscles: ['Hip External Rotators', 'Glutes', 'IT Band'],
    calsPerMin: 2, sets: 2, reps: '45–60s each side', rest: 30,
    instructions: 'From downward dog, bring one knee forward behind same-side wrist. Extend opposite leg behind. Sink hips toward floor. Fold forward for deeper stretch.',
    tip: 'Use a folded blanket under the hip if it doesn\'t reach the floor comfortably.',
    benefits: ['Hip flexibility', 'Glute release', 'Post-workout recovery'],
  },
];

export const getExercisesByCategory = (category) =>
  EXERCISES.filter(e => e.category === category);

export const getExerciseById = (id) =>
  EXERCISES.find(e => e.id === id);

export const getExercisesForEquipment = (equipmentList = []) =>
  EXERCISES.filter(e =>
    e.equipment === EQUIPMENT.BODYWEIGHT ||
    equipmentList.includes(e.equipment)
  );
